# yaml-language-server: $schema=https://docs.renovatebot.com/renovate-schema.json

allowedPostUpgradeCommands:
  - "^deno task lume upgrade --version"
  - "^pnpm install --frozen-lockfile --ignore-scripts$"
  - "^pnpm run build$"
  - "^pnpm run bundle$"
  - '^curl -fsSL https://deno.land/install.sh | sh && export PATH="$HOME/.deno/bin:$PATH"$'
onboardingConfigFileName: .renovaterc.json
